In [2]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# Load dataset
df = pd.read_csv("labeled_thermal_features.csv")

# Split features and target
X = df.drop(columns=["Frame", "Porosity Label"])
y = df["Porosity Label"]

# Initialize 5-fold CV
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Metrics storage
accuracies = []
conf_matrices = []
class_metrics = []

fold = 1
for train_index, test_index in skf.split(X, y):
    print(f"\n🔁 Fold {fold}")

    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Apply SMOTE
    smote = SMOTE(sampling_strategy=0.2, random_state=42)
    X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

    # XGBoost model
    xgb_classifier = xgb.XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        n_estimators=100,
        learning_rate=0.05,
        max_depth=3,
        subsample=0.7,
        colsample_bytree=0.7,
        reg_lambda=1,
        reg_alpha=0.5,
        use_label_encoder=False,
        random_state=42
    )

    # Train model
    xgb_classifier.fit(X_train_resampled, y_train_resampled)

    # Predict
    y_pred = xgb_classifier.predict(X_test)

    # Evaluate
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    report_dict = classification_report(y_test, y_pred, output_dict=True)

    # Per-class metrics
    per_class = {
        label: {
            "precision": round(metrics["precision"], 4),
            "recall": round(metrics["recall"], 4),
            "f1-score": round(metrics["f1-score"], 4),
            "support": int(metrics["support"])
        }
        for label, metrics in report_dict.items()
        if label in ['0', '1']
    }

    # Store results
    class_metrics.append(per_class)
    accuracies.append(accuracy)
    conf_matrices.append(conf_matrix)

    # Print fold results
    print(f"Accuracy: {accuracy:.4f}")
    print("Confusion Matrix:")
    print(conf_matrix)
    print("Per-class Metrics:")
    for label, scores in per_class.items():
        print(f"  Class {label}: {scores}")

    fold += 1

# =========================
# 📊 Final Summary
# =========================
print("\n📊 5-Fold Cross-Validation Summary:")
print(f"Average Accuracy: {np.mean(accuracies):.4f}")

# Aggregate average metrics
avg_metrics = {
    "0": {"precision": 0, "recall": 0, "f1-score": 0},
    "1": {"precision": 0, "recall": 0, "f1-score": 0}
}

for class_stat in class_metrics:
    for label in ["0", "1"]:
        for metric in ["precision", "recall", "f1-score"]:
            avg_metrics[label][metric] += class_stat[label][metric]

for label in ["0", "1"]:
    for metric in ["precision", "recall", "f1-score"]:
        avg_metrics[label][metric] = round(avg_metrics[label][metric] / 5, 4)

print("\n📈 Average Per-Class Metrics (across 5 folds):")
for label, scores in avg_metrics.items():
    print(f"  Class {label}: {scores}")

# Compute average confusion matrix
sum_conf_matrix = np.sum(conf_matrices, axis=0)
avg_conf_matrix = sum_conf_matrix / 5

print("\n🧮 Average Confusion Matrix (across 5 folds):")
print(np.round(avg_conf_matrix).astype(int))  # Show as integer matrix

# Optional: percentage format
conf_matrix_total = avg_conf_matrix.sum()
percent_matrix = (avg_conf_matrix / conf_matrix_total) * 100

print("\n📊 Average Confusion Matrix (Percentage):")
print(np.round(percent_matrix, 2))  # Show as percentage

# Save model from last fold
xgb_classifier.save_model("xgboost_anomaly_model_cv.json")
print("\n✅ Cross-validated XGBoost model saved as 'xgboost_anomaly_model_cv.json'.")



🔁 Fold 1
Accuracy: 0.9840
Confusion Matrix:
[[294   4]
 [  1  14]]
Per-class Metrics:
  Class 0: {'precision': 0.9966, 'recall': 0.9866, 'f1-score': 0.9916, 'support': 298}
  Class 1: {'precision': 0.7778, 'recall': 0.9333, 'f1-score': 0.8485, 'support': 15}

🔁 Fold 2
Accuracy: 0.9872
Confusion Matrix:
[[297   2]
 [  2  12]]
Per-class Metrics:
  Class 0: {'precision': 0.9933, 'recall': 0.9933, 'f1-score': 0.9933, 'support': 299}
  Class 1: {'precision': 0.8571, 'recall': 0.8571, 'f1-score': 0.8571, 'support': 14}

🔁 Fold 3


/Users/berkeayyildizli/ENS_Graduation_Project/.venv/lib/python3.10/site-packages/xgboost/training.py:183: UserWarning: [23:38:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/Users/berkeayyildizli/ENS_Graduation_Project/.venv/lib/python3.10/site-packages/xgboost/training.py:183: UserWarning: [23:38:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/Users/berkeayyildizli/ENS_Graduation_Project/.venv/lib/python3.10/site-packages/xgboost/training.py:183: UserWarning: [23:38:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


Accuracy: 0.9840
Confusion Matrix:
[[294   5]
 [  0  14]]
Per-class Metrics:
  Class 0: {'precision': 1.0, 'recall': 0.9833, 'f1-score': 0.9916, 'support': 299}
  Class 1: {'precision': 0.7368, 'recall': 1.0, 'f1-score': 0.8485, 'support': 14}

🔁 Fold 4
Accuracy: 0.9936
Confusion Matrix:
[[298   1]
 [  1  13]]
Per-class Metrics:
  Class 0: {'precision': 0.9967, 'recall': 0.9967, 'f1-score': 0.9967, 'support': 299}
  Class 1: {'precision': 0.9286, 'recall': 0.9286, 'f1-score': 0.9286, 'support': 14}

🔁 Fold 5
Accuracy: 0.9904
Confusion Matrix:
[[297   1]
 [  2  12]]
Per-class Metrics:
  Class 0: {'precision': 0.9933, 'recall': 0.9966, 'f1-score': 0.995, 'support': 298}
  Class 1: {'precision': 0.9231, 'recall': 0.8571, 'f1-score': 0.8889, 'support': 14}

📊 5-Fold Cross-Validation Summary:
Average Accuracy: 0.9879

📈 Average Per-Class Metrics (across 5 folds):
  Class 0: {'precision': 0.996, 'recall': 0.9913, 'f1-score': 0.9936}
  Class 1: {'precision': 0.8447, 'recall': 0.9152, 'f1-scor

/Users/berkeayyildizli/ENS_Graduation_Project/.venv/lib/python3.10/site-packages/xgboost/training.py:183: UserWarning: [23:38:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/Users/berkeayyildizli/ENS_Graduation_Project/.venv/lib/python3.10/site-packages/xgboost/training.py:183: UserWarning: [23:38:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
